name: W3C Deploy
author: 'Sid Vishnoi'
description: 'Build ReSpec/Bikeshed specs, validate output and publish to w3.org or GitHub pages'

inputs:
  type:
    description: Possible values - 'respec', 'bikeshed'
    required: true
  source:
    description: Source file path.
  validate-links:
    description: Validate hyperlinks
    default: true

runs:
  using: composite
  steps:
    - name: Setup toolchain
      run: |
        echo "::group::Setup toolchain"
        ${{ github.action_path }}/setup.sh
        echo "::endgroup::"
      shell: bash
      env:
        INPUTS_TYPE: ${{ inputs.type }}
        HOME: /home/runner
    - name: Generate Static HTML
      id: generate-html
      run: |
        echo "::group::Generate Static HTML"
        ${{ github.action_path }}/build.sh
        echo "::endgroup::"
      shell: bash
      env:
        INPUTS_TYPE: ${{ inputs.type }}
        INPUTS_SOURCE: ${{ inputs.source }}
    - name: Validate hyperlinks
      run: |
        echo "::group::Validate hyperlinks"
        ${{ github.action_path }}/validate-links.sh
        echo "::endgroup::"
      shell: bash
      env:
        INPUTS_VALIDATE_LINKS: ${{ inputs.validate-links }}
        OUTPUT_FILE: ${{ steps.generate-html.outputs.output }}
