name: W3C Deploy
author: 'Sid Vishnoi'
description: 'Build ReSpec/Bikeshed specs, validate output and publish to w3.org or GitHub pages'

inputs:
  type:
    description: Possible values - 'respec', 'bikeshed'
  source:
    description: Source file path.
  validate-links:
    description: Validate hyperlinks
    default: true
  validate-markup:
    description: Validate markup
    default: true

runs:
  using: composite
  steps:
    - name: Prepare
      id: prepare
      run: |
        echo "::group::Prepare"
        node ${{ github.action_path }}/prepare.js
        echo "::endgroup::"
      shell: bash
      env:
        INPUTS: ${{ toJSON(inputs) }}
    - name: Setup toolchain
      run: |
        echo "::group::Setup toolchain"
        ${{ github.action_path }}/setup.sh
        echo "::endgroup::"
      shell: bash
      env:
        INPUTS_TYPE: ${{ steps.prepare.outputs.type }}
        HOME: /home/runner
    - name: Generate Static HTML
      id: generate-html
      run: |
        echo "::group::Generate Static HTML"
        ${{ github.action_path }}/build.sh
        echo "::endgroup::"
      shell: bash
      env:
        INPUTS_TYPE: ${{ steps.prepare.outputs.type }}
        INPUTS_SOURCE: ${{ steps.prepare.outputs.source }}
    - name: Validate hyperlinks
      run: |
        echo "::group::Validate hyperlinks"
        ${{ github.action_path }}/validate-links.sh
        echo "::endgroup::"
      shell: bash
      env:
        INPUTS_VALIDATE_LINKS: ${{ steps.prepare.outputs.validate-links }}
        OUTPUT_FILE: ${{ steps.generate-html.outputs.output }}
    - name: Validate markup
      run: |
        echo "::group::Validate markup"
        ${{ github.action_path }}/validate-markup.sh
        echo "::endgroup::"
      shell: bash
      env:
        INPUTS_VALIDATE_MARKUP: ${{ steps.prepare.outputs.validate-markup }}
        OUTPUT_FILE: ${{ steps.generate-html.outputs.output }}
